INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (1, 'APOUASSA ANDZA', 'Verold', 'Homme', '2000-01-01');
INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (2, 'BARDOLPH', 'Scott ', 'Homme', '2000-01-01');
INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (3, 'BOUTAHAR', 'Soufiane ', 'Homme', '2000-01-01');
INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (4, 'CARUGE', 'David', 'Homme', '2000-01-01');
INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (5, 'GRAFF ', 'Antoine ', 'Homme', '2000-01-01');
INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (6, 'GUILLON ', 'Pablo ', 'Homme', '2000-01-01');
INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (7, 'JAOUEN ', 'Lucas ', 'Homme', '2000-01-01');
INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (8, 'JOVANOVIC', 'Ivan', 'Homme', '2000-01-01');
INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (9, 'KHAYRI ', 'Hassan ', 'Homme', '2000-01-01');
INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (10, 'MIHMAN ', 'Sacha ', 'Homme', '2000-01-01');
INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (11, 'MOULIN ', 'Etienne ', 'Homme', '2000-01-01');
INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (12, 'OMBAYA', 'Maroua', 'Femme', '2000-01-01');
INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (13, 'PULIN ', 'Basile ', 'Homme', '2000-01-01');
INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (14, 'SEDRATI ', 'Lucas ', 'Homme', '2000-01-01');
INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (15, 'ZAFAR', 'Zain', 'Homme', '2000-01-01');
INSERT INTO students (id, name, firstname, gender, birthDay) VALUES (16, 'APOUASSA ANDZA ', 'Verold ', 'Homme', '2000-01-01');